### ISSUE TITLE
check-mc-ping: Cannot connect to a replica set

### ISSUE THREAD

**Issue by Hellaenergy** [openshift/openshift_zabbix#9]
Even though OpenShift is able to connect to the MongoDB replica set via oo-admin-chk, check-mc-ping seems to be failing with the following error:

```
/opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/util/pool_manager.rb:265:in `get_valid_seed_node': Cannot connect to a replica set using seeds server1.example.com:27017, server2.example.com:27017, server3.example.com:27017 (Mongo::ConnectionFailure)
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/util/pool_manager.rb:171:in `connect_to_members'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/util/pool_manager.rb:66:in `block in connect'
    from <internal:prelude>:10:in `synchronize'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/util/pool_manager.rb:61:in `connect'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/mongo_replica_set_client.rb:202:in `block in connect'
    from <internal:prelude>:10:in `synchronize'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/mongo_replica_set_client.rb:191:in `connect'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/mongo_client.rb:693:in `setup'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/mongo_replica_set_client.rb:495:in `setup'
    from /opt/rh/ruby193/root/usr/share/gems/gems/mongo-1.9.2/lib/mongo/mongo_replica_set_client.rb:168:in `initialize'
    from /usr/share/zabbix/lib/openshift_mongo.rb:48:in `new'
    from /usr/share/zabbix/lib/openshift_mongo.rb:48:in `initialize'
    from /usr/share/zabbix/bin/check-mc-ping:99:in `new'
    from /usr/share/zabbix/bin/check-mc-ping:99:in `main'
    from /usr/share/zabbix/bin/check-mc-ping:182:in `<main>'
```

The MONGO entries in the /etc/openshift/broker.conf look like:

```
MONGO_HOST_PORT="server1.example.com:27017,server2.example.com:27017,server3.example.com:27017"
MONGO_USER="user"
MONGO_PASSWORD="password"
MONGO_DB="openshift_broker_db"
MONGO_TEST_DB="openshift_broker_test_db".
MONGO_SSL="true"
MONGO_WRITE_REPLICAS=1
```

**Comment by blentz** [comment]
That appears to be the issue, yes. The check does not appear to work with MONGO_SSL=true.
